# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69d4ef9d8f8ea00df92f880c952b33a78031b3961032cf2e13604322efd831e7d506358fa2647049b3dfd7a3b6c365ad5ca2d0a1b3ce1887ac165186a4ff93b3

test:
  secret_key_base: e3701efe5f1ccb33ae2ca8e7a8efad94d77cc8c43853a7c6a166c904ef2998304b930d38205b3054d8ed2cb11843034d113bfbcab6ab349b124fa6f0b69bf82a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
